import Header from "../app/header/page";
import "../public/css/globals.css";
import Footer from "../app/footer/page";
import TopButton from "../components/TopButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="de">
      <body>
        <Header />
        {children}
        <TopButton/>
        <Footer />
      </body>
    </html>
  );
}
